version: "3"

services:
#    bot:
#        image: theatrebot
#        build:
#            context: .
#            dockerfile: bot/Dockerfile
#        restart: always
#        networks:
#            - health
#        env_file:
#            - bot/.env_dist
#        volumes:
#            - ./my_db.db:/app/my_db.db
#            - ./media:/app/media
#            - ./.env_dist:/app/.env_dist
#            - ./resources:/app/resources

    webserver:
        build:
            context: .
            dockerfile: nginx/Dockerfile
        image: digitalocean.com/webserver:latest
        container_name: webserver
        environment:
            APP_DEBUG: "true"
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - nginxdata:/var/log/nginx
        networks:
            - health



networks:
  health:
    driver: bridge


volumes:
  nginxdata:
    driver: local